<?php

return [

	'base_roles' => [
		'moderator', // 0
		'admin',     // 1
		'assistant', // 2
		'employee',  // 3
		'tutor',     // 4
		'student',   // 5
		'visitor',   // 6
		'guest',     // 7
	],
      // role moderator has all permissions by default
	
	'permissions' => [ // name, group, number in group, list of base roles for permission
		['view_backend_pages',    'base',    [0, 0],    [1,2,3,4,5]],

		['access_access',         'access',  [1, 0],   [1]],
		['show_roles',            'access',  [1, 10],  [1]],
		['crud_roles',            'access',  [1, 20],  [1]],
		['show_permissions',      'access',  [1, 30],  [1]],
		['update_permissions',    'access',  [1, 40],  [1]],
		['bind_permissions',      'access',  [1, 50],  [1]],
		['bind_roles',            'access',  [1, 60],  [1]],

		['access_struct',         'unit',    [2, 0],   [1,4]],
            ['show_kinds',            'unit',    [2, 10],  [1,4]],
            ['crud_kinds',            'unit',    [2, 20],  [1,4]],
            ['show_types',            'unit',    [2, 30],  [1,4]],
            ['crud_types',            'unit',    [2, 40],  [1,4]],
		['show_units',            'unit',    [2, 50],  [1,4]],
		['crud_units',            'unit',    [2, 60],  [1,4]],
		['bind_units',            'unit',    [2, 70],  [1,4]],

		['access_module',         'module',  [3, 0],   [1,4]],
		['show_modules',          'module',  [3, 30],  [1,4]],
		['crud_modules',          'module',  [3, 40],  [1,4]],
            ['bind_modules',          'module',  [3, 50],  [1,4]],

		['access_entity',         'entity',  [4, 0],   [1,4]],
		['show_entity_types',     'entity',  [4, 10],  [1,4]],
		['crud_entity_types',     'entity',  [4, 20],  [1,4]],
		['show_entities',         'entity',  [4, 30],  [1,4]],
		['crud_entities',         'entity',  [4, 40],  [1,4]],
		['show_sections',         'entity',  [4, 50],  [1,4]],
		['crud_sections',         'entity',  [4, 60],  [1,4]],
		['crud_common_sections',  'entity',  [4, 70],  [1,4]],
		['show_option_types',     'entity',  [4, 80],  [1,4]],
		['crud_option_types',     'entity',  [4, 90],  [1,4]],
		['show_options',          'entity',  [4, 100], [1,4]],
		['crud_options',          'entity',  [4, 110], [1,4]],
		['bind_entities',         'entity',  [4, 120], [1,4]],

		['access_union',          'union',   [5, 0],   [1,4]],
		['show_union_types',      'union',   [5, 10],  [1,4]],
		['crud_union_types',      'union',   [5, 20],  [1,4]],
            ['show_unions',           'union',   [5, 30],  [1,4]],
            ['crud_unions',           'union',   [5, 40],  [1,4]],
		['bind_unions',           'union',   [5, 50],  [1,4]],
		//['change_union_kind',     'union',   [5, 60],  [1,4]],

		['access_users',          'usr',     [6, 0],   [1,4]],
            ['show_admin',            'usr',     [6, 10],  [1]],
            ['crud_admin',            'usr',     [6, 20],  [1]],
		['show_users',            'usr',     [6, 30],  [1,4]],
		['crud_users',            'usr',     [6, 40],  [1,4]],
            ['bind_users',            'usr',     [6, 50],  [1,4]],
		['make_global_users',     'usr',     [6, 60],  [1,4]],

		['access_settings',       'sttg',    [7, 0],   [1]],
		['change_settings',       'sttg',    [7, 10],  [1]],
		['change_decor',          'sttg',    [7, 20],  [1]],

		['access_chatable',       'chat',    [8, 0],   [1,4]],
		['access_chat_admin',     'chat',    [8, 10],  [1,4]],
		['access_chat_employee',  'chat',    [8, 20],  [1,4]],
		['access_chat_tutor',     'chat',    [8, 30],  [1,4]],
		['access_chat_asistant',  'chat',    [8, 40],  [1,4]],
		['access_chat_student',   'chat',    [8, 50],  [1,4]],
		['access_chat_visitor',   'chat',    [8, 60],  [1,4]],
		['access_chat_guest',     'chat',    [8, 70],  [1,4]],
		['crud_chatrooms',        'chat',    [8, 80],  [1,4]],
	],


	'languages' => [
            'ab' => 'Abkhazian',
            'aa' => 'Afar',
            'af' => 'Afrikaans',
            'ak' => 'Akan',
            'sq' => 'Albanian',
            'am' => 'Amharic',
            'ar' => 'Arabic',
            'an' => 'Aragonese',
            'hy' => 'Armenian',
            'as' => 'Assamese',
            'av' => 'Avaric',
            'ae' => 'Avestan',
            'ay' => 'Aymara',
            'az' => 'Azerbaijani',
            'bm' => 'Bambara',
            'ba' => 'Bashkir',
            'eu' => 'Basque',
            'be' => 'Belarusian',
            'bn' => 'Bengali',
            'bh' => 'Bihari languages',
            'bi' => 'Bislama',
            'bs' => 'Bosnian',
            'br' => 'Breton',
            'bg' => 'Bulgarian',
            'my' => 'Burmese',
            'ca' => 'Catalan, Valencian',
            'km' => 'Central Khmer',
            'ch' => 'Chamorro',
            'ce' => 'Chechen',
            'ny' => 'Chichewa, Chewa, Nyanja',
            'zh' => 'Chinese',
            'cu' => 'Church Slavonic, Old Bulgarian, Old Church Slavonic',
            'cv' => 'Chuvash',
            'kw' => 'Cornish',
            'co' => 'Corsican',
            'cr' => 'Cree',
            'hr' => 'Croatian',
            'cs' => 'Czech',
            'da' => 'Danish',
            'dv' => 'Divehi, Dhivehi, Maldivian',
            'nl' => 'Dutch, Flemish',
            'dz' => 'Dzongkha',
            'en' => 'English',
            'eo' => 'Esperanto',
            'et' => 'Estonian',
            'ee' => 'Ewe',
            'fo' => 'Faroese',
            'fj' => 'Fijian',
            'fi' => 'Finnish',
            'fr' => 'French',
            'ff' => 'Fulah',
            'gd' => 'Gaelic, Scottish Gaelic',
            'gl' => 'Galician',
            'lg' => 'Ganda',
            'ka' => 'Georgian',
            'de' => 'German',
            'ki' => 'Gikuyu, Kikuyu',
            'el' => 'Greek (Modern)',
            'kl' => 'Greenlandic, Kalaallisut',
            'gn' => 'Guarani',
            'gu' => 'Gujarati',
            'ht' => 'Haitian, Haitian Creole',
            'ha' => 'Hausa',
            'he' => 'Hebrew',
            'hz' => 'Herero',
            'hi' => 'Hindi',
            'ho' => 'Hiri Motu',
            'hu' => 'Hungarian',
            'is' => 'Icelandic',
            'io' => 'Ido',
            'ig' => 'Igbo',
            'id' => 'Indonesian',
            'ia' => 'Interlingua (International Auxiliary Language Association)',
            'ie' => 'Interlingue',
            'iu' => 'Inuktitut',
            'ik' => 'Inupiaq',
            'ga' => 'Irish',
            'it' => 'Italian',
            'ja' => 'Japanese',
            'jv' => 'Javanese',
            'kn' => 'Kannada',
            'kr' => 'Kanuri',
            'ks' => 'Kashmiri',
            'kk' => 'Kazakh',
            'rw' => 'Kinyarwanda',
            'kv' => 'Komi',
            'kg' => 'Kongo',
            'ko' => 'Korean',
            'kj' => 'Kwanyama, Kuanyama',
            'ku' => 'Kurdish',
            'ky' => 'Kyrgyz',
            'lo' => 'Lao',
            'la' => 'Latin',
            'lv' => 'Latvian',
            'lb' => 'Letzeburgesch, Luxembourgish',
            'li' => 'Limburgish, Limburgan, Limburger',
            'ln' => 'Lingala',
            'lt' => 'Lithuanian',
            'lu' => 'Luba-Katanga',
            'mk' => 'Macedonian',
            'mg' => 'Malagasy',
            'ms' => 'Malay',
            'ml' => 'Malayalam',
            'mt' => 'Maltese',
            'gv' => 'Manx',
            'mi' => 'Maori',
            'mr' => 'Marathi',
            'mh' => 'Marshallese',
            'ro' => 'Moldovan, Moldavian, Romanian',
            'mn' => 'Mongolian',
            'na' => 'Nauru',
            'nv' => 'Navajo, Navaho',
            'nd' => 'Northern Ndebele',
            'ng' => 'Ndonga',
            'ne' => 'Nepali',
            'se' => 'Northern Sami',
            'no' => 'Norwegian',
            'nb' => 'Norwegian Bokmål',
            'nn' => 'Norwegian Nynorsk',
            'ii' => 'Nuosu, Sichuan Yi',
            'oc' => 'Occitan (post 1500)',
            'oj' => 'Ojibwa',
            'or' => 'Oriya',
            'om' => 'Oromo',
            'os' => 'Ossetian, Ossetic',
            'pi' => 'Pali',
            'pa' => 'Panjabi, Punjabi',
            'ps' => 'Pashto, Pushto',
            'fa' => 'Persian',
            'pl' => 'Polish',
            'pt' => 'Portuguese',
            'qu' => 'Quechua',
            'rm' => 'Romansh',
            'rn' => 'Rundi',
            'ru' => 'Russian',
            'sm' => 'Samoan',
            'sg' => 'Sango',
            'sa' => 'Sanskrit',
            'sc' => 'Sardinian',
            'sr' => 'Serbian',
            'sn' => 'Shona',
            'sd' => 'Sindhi',
            'si' => 'Sinhala, Sinhalese',
            'sk' => 'Slovak',
            'sl' => 'Slovenian',
            'so' => 'Somali',
            'st' => 'Sotho, Southern',
            'nr' => 'South Ndebele',
            'es' => 'Spanish, Castilian',
            'su' => 'Sundanese',
            'sw' => 'Swahili',
            'ss' => 'Swati',
            'sv' => 'Swedish',
            'tl' => 'Tagalog',
            'ty' => 'Tahitian',
            'tg' => 'Tajik',
            'ta' => 'Tamil',
            'tt' => 'Tatar',
            'te' => 'Telugu',
            'th' => 'Thai',
            'bo' => 'Tibetan',
            'ti' => 'Tigrinya',
            'to' => 'Tonga (Tonga Islands)',
            'ts' => 'Tsonga',
            'tn' => 'Tswana',
            'tr' => 'Turkish',
            'tk' => 'Turkmen',
            'tw' => 'Twi',
            'ug' => 'Uighur, Uyghur',
            'uk' => 'Ukrainian',
            'ur' => 'Urdu',
            'uz' => 'Uzbek',
            've' => 'Venda',
            'vi' => 'Vietnamese',
            'vo' => 'Volap_k',
            'wa' => 'Walloon',
            'cy' => 'Welsh',
            'fy' => 'Western Frisian',
            'wo' => 'Wolof',
            'xh' => 'Xhosa',
            'yi' => 'Yiddish',
            'yo' => 'Yoruba',
            'za' => 'Zhuang, Chuang',
            'zu' => 'Zulu'
	],

      'currencies' => [

            "AFGHANISTAN, Afghani, AFN, 971",
            "ALBANIA, Lek, ALL, 008",
            "ALGERIA, Algerian Dinar, DZD, 012",
            "AMERICAN SAMOA, US Dollar, USD, 840",
            "ANDORRA, Euro, EUR, 978",
            "ANGOLA, Kwanza, AOA, 973",
            "ANGUILLA, East Caribbean Dollar, XCD, 951",        
            "ANTIGUA AND BARBUDA, East Caribbean Dollar, XCD, 951",
            "ARGENTINA, Argentine Peso, ARS, 032",
            "ARMENIA, Armenian Dram, AMD, 051",
            "ARUBA, Aruban Florin, AWG, 533",
            "AUSTRALIA, Australian Dollar, AUD, 036",
            "AUSTRIA, Euro, EUR, 978",
            "AZERBAIJAN, Azerbaijanian Manat, AZN, 944",
            "BAHAMAS, Bahamian Dollar, BSD, 044",
            "BAHRAIN, Bahraini Dinar, BHD, 048",
            "BANGLADESH, Taka, BDT, 050",
            "BARBADOS, Barbados Dollar, BBD, 052",
            "BELARUS, Belarussian Ruble, BYR, 974",
            "BELGIUM, Euro, EUR, 978",
            "BELIZE, Belize Dollar, BZD, 084",
            "BENIN, CFA Franc BCEAO, XOF, 952",
            "BERMUDA, Bermudian Dollar, BMD, 060",
            "BHUTAN, Ngultrum, BTN, 064",
            "BHUTAN, Indian Rupee,INR, 356",
            "BOLIVIA (PLURINATIONAL STATE OF), Boliviano, BOB, 068",
            "BOLIVIA (PLURINATIONAL STATE OF), Mvdol, BOV, 984",
            "BONAIRE SINT EUSTATIUS AND SABA, US Dollar, USD, 840",
            "BOSNIA AND HERZEGOVINA, Convertible Mark, BAM, 977",
            "BOTSWANA, Pula, BWP, 072",
            "BOUVET ISLAND, Norwegian Krone, NOK, 578",
            "BRAZIL, Brazilian Real, BRL, 986",
            "BRITISH INDIAN OCEAN TERRITORY, US Dollar, USD, 840",
            "BRUNEI DARUSSALAM, Brunei Dollar, BND, 096",
            "BULGARIA, Bulgarian Lev, BGN, 975",
            "BURKINA FASO, CFA Franc BCEAO, XOF, 952",
            "BURUNDI, Burundi Franc, BIF, 108",
            "CABO VERDE, Cabo Verde Escudo, CVE, 132",
            "CAMBODIA, Riel, KHR, 116",
            "CAMEROON, CFA Franc BEAC, XAF, 950",
            "CANADA, Canadian Dollar, CAD, 124",
            "CAYMAN ISLANDS, Cayman Islands Dollar, KYD, 136",
            "CENTRAL AFRICAN REPUBLIC, CFA Franc BEAC, XAF, 950",
            "CHAD, CFA Franc BEAC, XAF, 950",
            "CHILE, Unidad de Fomento, CLF, 990",
            "CHILE, Chilean Peso, CLP, 152",
            "CHINA, Yuan Renminbi, CNY,156",
            "CHRISTMAS ISLAND,  Australian Dollar,  AUD, 036",
            "COCOS (KEELING) ISLANDS, Australian Dollar, AUD, 036",
            "COLOMBIA, Colombian Peso,  COP, 170",
            "COLOMBIA, Unidad de Valor Real, COU, 970",
            "COMOROS, Comoro Franc, KMF, 174",
            "CONGO (THE DEMOCRATIC REPUBLIC OF THE), Congolese Franc, CDF, 976",
            "CONGO, CFA Franc BEAC, XAF, 950",
            "COOK ISLANDS, New Zealand Dollar, NZD, 554",
            "COSTA RICA, Costa Rican Colon, CRC, 188",
            "CROATIA, Kuna, HRK, 191",
            "CUBA, Peso Convertible, CUC, 931",
            "CUBA, Cuban Peso, CUP, 192",
            "CURAÇAO, Netherlands Antillean Guilder, ANG, 532",
            "CYPRUS, Euro, EUR, 978",
            "CZECH REPUBLIC, Czech Koruna, CZK, 203",
            "CÔTE D\'IVOIRE, CFA Franc BCEAO, XOF, 952",
            "DENMARK, Danish Krone, DKK, 208",
            "DJIBOUTI, Djibouti Franc, DJF, 262",
            "DOMINICA, East Caribbean Dollar, XCD, 951",
            "DOMINICAN REPUBLIC, Dominican Peso, DOP, 214",
            "ECUADOR, US Dollar, USD, 840",
            "EGYPT, Egyptian Pound, EGP, 818",
            "EL SALVADOR, El Salvador Colon, SVC, 222",
            "EL SALVADOR, US Dollar, USD, 840",
            "EQUATORIAL GUINEA, CFA Franc BEAC, XAF, 950",
            "ERITREA, Nakfa, ERN, 232",
            "ESTONIA, Euro, EUR, 978",
            "ETHIOPIA, Ethiopian Birr, ETB, 230",
            "EUROPEAN UNION, Euro, EUR, 978",
            "FALKLAND ISLANDS [MALVINAS], Falkland Islands Pound, FKP, 238",
            "FAROE ISLANDS, Danish Krone, DKK, 208",
            "FIJI, Fiji Dollar, FJD, 242",
            "FINLAND, Euro, EUR, 978",
            "FRANCE, Euro, EUR, 978",
            "FRENCH GUIANA, Euro, EUR, 978",
            "FRENCH POLYNESIA, CFP Franc, XPF, 953",
            "FRENCH SOUTHERN TERRITORIES, Euro, EUR, 978",
            "GABON, CFA Franc BEAC, XAF, 950",
            "GAMBIA, Dalasi, GMD, 270",
            "GEORGIA, Lari, GEL, 981",
            "GERMANY, Euro, EUR, 978",
            "GHANA, Ghana Cedi, GHS, 936",
            "GIBRALTAR, Gibraltar Pound, GIP, 292",
            "GREECE, Euro, EUR, 978",
            "GREENLAND, Danish Krone, DKK, 208",
            "GRENADA, East Caribbean Dollar, XCD, 951",
            "GUADELOUPE, Euro, EUR, 978",
            "GUAM, US Dollar, USD, 840",
            "GUATEMALA, Quetzal, GTQ, 320",
            "GUERNSEY, Pound Sterling, GBP, 826",
            "GUINEA, Guinea Franc, GNF, 324",
            "GUINEA-BISSAU, CFA Franc BCEAO, XOF, 952",
            "GUYANA, Guyana Dollar, GYD, 328",
            "HAITI, Gourde, HTG, 332",
            "HAITI, US Dollar, USD, 840",
            "HEARD ISLAND AND McDONALD ISLANDS, Australian Dollar, AUD, 036",
            "HOLY SEE, Euro, EUR, 978",
            "HONDURAS, Lempira, HNL, 340",
            "HONG KONG, Hong Kong Dollar, HKD, 344",
            "HUNGARY, Forint, HUF, 348",
            "ICELAND, Iceland Krona, ISK, 352",
            "INDIA, Indian Rupee, INR, 356",
            "INDONESIA, Rupiah, IDR, 360",
            "INTERNATIONAL MONETARY FUND, SDR (Special Drawing Right), XDR, 960",
            "IRAN (ISLAMIC REPUBLIC OF), Iranian Rial, IRR, 364",
            "IRAQ, Iraqi Dinar, IQD, 368",
            "IRELAND, Euro, EUR, 978",
            "ISLE OF MAN, Pound Sterling, GBP, 826",
            "ISRAEL, New Israeli Sheqel, ILS, 376",
            "ITALY, Euro, EUR, 978",
            "JAMAICA, Jamaican Dollar, JMD, 388",
            "JAPAN, Yen, JPY, 392",
            "JERSEY, Pound Sterling, GBP, 826",
            "JORDAN, Jordanian Dinar, JOD, 400",
            "KAZAKHSTAN, Tenge, KZT, 398",
            "KENYA, Kenyan Shilling, KES, 404",
            "KIRIBATI, Australian Dollar, AUD, 036",
            "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF), North Korean Won, KPW, 408",
            "KOREA (THE REPUBLIC OF), Won, KRW, 410",
            "KUWAIT, Kuwaiti Dinar, KWD, 414",
            "KYRGYZSTAN, Som, KGS, 417",
            "LAO PEOPLE’S DEMOCRATIC REPUBLIC, Kip, LAK, 418",
            "LATVIA, Euro, EUR, 978",
            "LEBANON, Lebanese Pound, LBP, 422",
            "LESOTHO, Loti, LSL, 426",
            "LESOTHO, Rand, ZAR, 710",
            "LIBERIA, Liberian Dollar, LRD, 430",
            "LIBYA, Libyan Dinar, LYD, 434",
            "LIECHTENSTEIN, Swiss Franc, CHF, 756",
            "LITHUANIA, Euro, EUR, 978",
            "LUXEMBOURG, Euro, EUR, 978",
            "MACAO, Pataca, MOP, 446",
            "MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF), Denar, MKD, 807",
            "MADAGASCAR, Malagasy Ariary, MGA, 969",
            "MALAWI, Kwacha, MWK, 454",
            "MALAYSIA, Malaysian Ringgit, MYR, 458",
            "MALDIVES, Rufiyaa, MVR, 462",
            "MALI, CFA Franc BCEAO, XOF, 952",
            "MALTA, Euro, EUR, 978",
            "MARSHALL ISLANDS, US Dollar, USD, 840",
            "MARTINIQUE, Euro, EUR, 978",
            "MAURITANIA, Ouguiya, MRU, 478",
            "MAURITIUS, Mauritius Rupee, MUR, 480",
            "MAYOTTE, Euro, EUR, 978",
            "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP, ADB Unit of Account, XUA, 965",
            "MEXICO, Mexican Peso, MXN, 484",
            "MEXICO, Mexican Unidad de Inversion (UDI), MXV, 979",
            "MICRONESIA (FEDERATED STATES OF), US Dollar, USD, 840",
            "MOLDOVA (THE REPUBLIC OF), Moldovan Leu, MDL, 498",
            "MONACO, Euro, EUR, 978",
            "MONGOLIA, Tugrik, MNT, 496",
            "MONTENEGRO, Euro, EUR, 978",
            "MONTSERRAT, East Caribbean Dollar, XCD, 951",
            "MOROCCO, Moroccan Dirham, MAD, 504",
            "MOZAMBIQUE, Mozambique Metical, MZN, 943",
            "MYANMAR, Kyat, MMK, 104",
            "NAMIBIA, Namibia Dollar, NAD, 516",
            "NAMIBIA, Rand, ZAR, 710",
            "NAURU, Australian Dollar, AUD, 036",
            "NEPAL, Nepalese Rupee, NPR, 524",
            "NETHERLANDS, Euro, EUR, 978",
            "NEW CALEDONIA, CFP Franc, XPF, 953",
            "NEW ZEALAND, New Zealand Dollar, NZD, 554",
            "NICARAGUA, Cordoba Oro, NIO, 558",
            "NIGER, CFA Franc BCEAO, XOF, 952",
            "NIGERIA, Naira, NGN, 566",
            "NIUE, New Zealand Dollar, NZD, 554",
            "NORFOLK ISLAND, Australian Dollar, AUD, 036",
            "NORTHERN MARIANA ISLANDS, US Dollar, USD, 840",
            "NORWAY, Norwegian Krone, NOK, 578",
            "OMAN, Rial Omani, OMR, 512",
            "PAKISTAN, Pakistan Rupee, PKR, 586",
            "PALAU, US Dollar, USD, 840",
            "PALESTINE, New Israeli Sheqel, ILS, 376",  
            "PANAMA, Balboa, PAB, 590",
            "PANAMA, US Dollar, USD, 840",
            "PAPUA NEW GUINEA, Kina, PGK, 598",
            "PARAGUAY, Guarani, PYG, 600",
            "PERU, Nuevo Sol, PEN, 604",
            "PHILIPPINES, Philippine Peso, PHP, 608",
            "PITCAIRN, New Zealand Dollar, NZD, 554",
            "POLAND, Zloty, PLN, 985",
            "PORTUGAL, Euro, EUR, 978",
            "PUERTO RICO, US Dollar, USD, 840",
            "QATAR, Qatari Rial, QAR, 634",
            "ROMANIA, Romanian Leu, RON, 946",
            "RUSSIAN FEDERATION, Russian Ruble, RUB, 643",
            "RWANDA, Rwanda Franc, RWF, 646",
            "RÉUNION, Euro, EUR, 978",
            "SAINT BARTHÉLEMY, Euro, EUR, 978",
            "SAINT HELENA, Saint Helena Pound, SHP, 654",
            "SAINT KITTS, Caribbean Dollar, XCD, 951",
            "SAINT LUCIA, East Caribbean Dollar, XCD, 951",
            "SAINT MARTIN (FRENCH PART), Euro, EUR, 978",
            "SAINT PIERRE AND MIQUELON, Euro, EUR, 978",
            "SAINT VINCENT AND THE GRENADINES, East Caribbean Dollar, XCD, 951",
            "SAMOA, Tala, WST, 882",
            "SAN MARINO, Euro, EUR, 978",
            "SAO TOME AND PRINCIPE, Dobra, STN, 678",
            "SAUDI ARABIA, Saudi Riyal, SAR, 682",
            "SENEGAL, CFA Franc BCEAO, XOF, 952",
            "SERBIA, Serbian Dinar, RSD, 941",
            "SEYCHELLES, Seychelles Rupee, SCR, 690",
            "SIERRA LEONE, Leone, SLL, 694",
            "SINGAPORE, Singapore Dollar, SGD, 702",
            "SINT MAARTEN (DUTCH PART), Netherlands Antillean Guilder, ANG, 532",
            "SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS, Sucre, XSU, 994",
            "SLOVAKIA, Euro, EUR, 978",
            "SLOVENIA, Euro, EUR, 978",
            "SOLOMON ISLANDS, Solomon Islands Dollar, SBD, 090",
            "SOMALIA, Somali Shilling, SOS, 706",
            "SOUTH AFRICA, Rand, ZAR, 710", 
            "SOUTH SUDAN, South Sudanese Pound, SSP, 728",
            "SPAIN, Euro, EUR, 978",
            "SRI LANKA, Sri Lanka Rupee, LKR, 144",
            "SUDAN, Sudanese Pound, SDG, 938",
            "SURINAME, Surinam Dollar, SRD, 968",
            "SVALBARD AND JAN MAYEN, Norwegian Krone, NOK, 578",
            "SWAZILAND, Lilangeni, SZL, 748",
            "SWEDEN, Swedish Krona, SEK, 752",
            "SWITZERLAND, WIR Euro, CHE, 947",
            "SWITZERLAND, Swiss Franc, CHF, 756",
            "SWITZERLAND, WIR Franc, CHW, 948",
            "SYRIAN ARAB REPUBLIC, Syrian Pound, SYP, 760",
            "TAIWAN (PROVINCE OF CHINA), New Taiwan Dollar, TWD, 901",
            "TAJIKISTAN, Somoni, TJS, 972",
            "TANZANIA, Tanzanian Shilling, TZS, 834",
            "THAILAND, Baht, THB, 764",
            "TIMOR-LESTE, US Dollar, USD, 840",
            "TOGO, CFA Franc BCEAO, XOF, 952",
            "TOKELAU, New Zealand Dollar, NZD, 554",
            "TONGA, Pa’anga, TOP, 776",
            "TRINIDAD AND TOBAGO, Trinidad and Tobago Dollar, TTD, 780",
            "TUNISIA, Tunisian Dinar, TND, 788",
            "TURKEY, Turkish Lira, TRY, 949",
            "TURKMENISTAN, Turkmenistan New Manat, TMT, 934",
            "TURKS AND CAICOS ISLANDS, US Dollar, USD, 840",
            "TUVALU, Australian Dollar, AUD, 036",
            "UGANDA, Uganda Shilling, UGX, 800",
            "UKRAINE, Hryvnia, UAH, 980",
            "UNITED ARAB EMIRATES, UAE Dirham, AED, 784",
            "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND, Pound Sterling, GBP, 826",
            "UNITED STATES MINOR OUTLYING ISLANDS, US Dollar, USD, 840",
            "UNITED STATES OF AMERICA, US Dollar, USD, 840",
            "UNITED STATES OF AMERICA,  US Dollar, USN, 997",
            "URUGUAY, Uruguay Peso en Unidades Indexadas, UYI, 940",
            "URUGUAY, Peso Uruguayo, UYU, 858",
            "UZBEKISTAN, Uzbekistan Sum, UZS, 860",
            "VANUATU, Vatu, VUV, 548",
            "VENEZUELA (BOLIVARIAN REPUBLIC OF), Bolivar, VEF, 937",
            "VIET NAM, Dong, VND, 704",
            "VIRGIN ISLANDS (BRITISH), US Dollar, USD, 840",
            "VIRGIN ISLANDS (U.S.), US Dollar, USD, 840",
            "WALLIS AND FUTUNA, CFP Franc, XPF, 953",
            "WESTERN SAHARA, Moroccan Dirham, MAD, 504",
            "YEMEN, Yemeni Rial, YER, 886",
            "ZAMBIA, Zambian Kwacha, ZMW, 967",
            "ZIMBABWE, Zimbabwe Dollar, ZWL, 932",
            "ÅLAND ISLANDS, Euro, EUR, 978",
      ],

      'items' => ['foundations', 'users', 'roles', 'permissions', 'kinds', 'types', 'units', 'unions'],

      'allows' => [
            'roles' => [ 
                  'bind' => [
                        [ 'ikey'=>'permissions', 'allow' => true ],
                        [ 'ikey'=>'users',       'allow' => true ],
                  ],
                  'add' => [],
            ],
      ],

      'settings' => [ // name, default value, for
            ['allow_remote',                  'yes',         'base'   ],
            ['allow_temporay',                'yes',         'base'   ],
            ['allow_chatable',                'yes',         'base'   ],
            ['allow_kind_logo',               'yes',         'base'   ],
            ['allow_unit_logo',               'yes',         'base'   ],
            ['date_interval',                 '6',           'base'   ], // valid date by now (+/-years)
            ['date_format',                   'dmy-',        'base'   ], // key for data from settings
            ['time_zone',                     'UTC',         'base'   ],

            ['max_count_unit_sections',       '20',          'struct' ],
            ['max_count_user_sections',       '5',           'struct' ],
            ['optiom_type_strictly_option',   'yes',         'struct' ],
            ['unit_type_strictly_unit',       'yes',         'struct' ],
            ['optiom_type_strictly_options',  'yes',         'struct' ],

            ['binding_options_by_group',      'group',       'group'  ], // no/group/grouptype
            ['allow_bind_groups_options',     'yes',         'group'  ],                
            ['group_type_strictly_group',     'yes',         'group'  ],
            
            ['default_item_chatable',         'yes',         'chat'   ],

      ],

      'decors' => [ // name, default value, for
            ['site_background_color',         'white',       'base'   ],
            ['main_nav_background_color',     'white',       'base'   ],
      ],

];